adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.users_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.users_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.users_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.products_create, name='products_create'),
    path('products/read/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='product_read'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/update/<int:pk>/', adminapp.products_update, name='products_update'),
    path('products/delete/<int:pk>/', adminapp.products_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_stuff/', include('adminapp.urls', namespace='admin_stuff')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from django.db import connection
from django.db.models import F
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from adminapp.views import db_profile_by_type
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = "__all__"

    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


@user_passes_test(lambda u: u.is_superuser)
def users_create(request):
    title = "пользователи / создание"
    if request.method == 'POST':
        update_form = ShopUserRegisterForm(request.POST, request.FILES)

        if update_form.is_valid():
            update_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        update_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'update_form': update_form
    }
    return render(request, "adminapp/user_update.html", context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка / пользователи'
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     context = {
#         'title': title,
#         'objects': users_list
#     }
#     return render(request, 'adminapp/users.html', context)

class UsersListView(ListView):
    model = ShopUser
    template_name = "adminapp/users.html"

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(is_active=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи / список'
        return context


@user_passes_test(lambda u: u.is_superuser)
def users_update(request, pk):
    title = "пользователи / редактирование"

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == "POST":
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("admin:users"))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    context = {
        "title": title,
        "update_form": edit_form
    }
    return render(request, "adminapp/user_update.html", context)


@user_passes_test(lambda u: u.is_superuser)
def users_delete(request, pk):
    title = "пользователи / удаление"
    user_item = get_object_or_404(ShopUser, pk=pk)
    if request.method == "POST":
        if user_item.is_active:
            user_item.is_active = False
        else:
            user_item.is_active = True
        user_item.save()
        return HttpResponseRedirect(reverse("admin:users"))

    context = {
        "title": title,
        "user_to_delete": user_item
    }
    return render(request, "adminapp/user_delete.html", context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка / категории'
    categories_list = ProductCategory.objects.all().order_by('-is_active', '-id')
    context = {
        'title': title,
        'objects': categories_list
    }
    return render(request, 'adminapp/categories.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = "категории / создание"
#     if request.method == 'POST':
#         update_form = ProductCategoryEditForm(request.POST, request.FILES)
#
#         if update_form.is_valid():
#             update_form.save()
#             return HttpResponseRedirect(reverse('admin:categories'))
#     else:
#         update_form = ProductCategoryEditForm()
#
#     context = {
#         'title': title,
#         'update_form': update_form
#     }
#     return render(request, "adminapp/category_update.html", context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")

    # fields = "__all__"

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / создание'
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")

    # fields = "__all__"

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / редактирование'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = "adminapp/category_delete.html"

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / удаление'
        return context

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.is_active:
            obj.is_active = False
        else:
            obj.is_active = True
        obj.save()

        return HttpResponseRedirect(reverse("admin:categories"))


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = "категории / редактирование"
#
#     category_item = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         update_form = ProductCategoryEditForm(request.POST, request.FILES, instance=category_item)
#
#         if update_form.is_valid():
#             update_form.save()
#             return HttpResponseRedirect(reverse('admin:categories'))
#     else:
#         update_form = ProductCategoryEditForm(instance=category_item)
#
#     context = {
#         'title': title,
#         'update_form': update_form
#     }
#     return render(request, "adminapp/category_update.html", context)


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     title = "категории / удаление"
#     category_item = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == "POST":
#         if category_item.is_active:
#             category_item.is_active = False
#         else:
#             category_item.is_active = True
#         category_item.save()
#         return HttpResponseRedirect(reverse("admin:categories"))
#
#     context = {
#         "title": title,
#         "category_to_delete": category_item
#     }
#     return render(request, "adminapp/category_delete.html", context)


@user_passes_test(lambda u: u.is_superuser)
def products_create(request, pk):
    title = "категории / удаление"
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse("adminapp:products", args=[pk]))
    else:
        product_form = ProductEditForm()

    context = {
        "title": title,
        "update_form": product_form,
        "category": category
    }
    return render(request, "adminapp/product_update.html", context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "adminapp/product_read.html"

    method_decorator(user_passes_test(lambda user: user.is_superuser))

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def product_read(request, pk):
#     title = "продукт / подробнее"
#     product = get_object_or_404(Product, pk=pk)
#     context = {
#         "title": title,
#         "object": product
#     }
#     return render(request, "adminapp/product_read.html", context)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk, page=1):
    title = 'админка / товары'
    category_item = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category=category_item).order_by('-id')

    # paginator = Paginator(products_list, 5)
    # try:
    #     products_paginator = paginator.page(page)
    # except PageNotAnInteger:
    #     products_paginator = paginator.page(1)
    # except EmptyPage:
    #     products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'objects': products_list,
        'category': category_item
    }
    return render(request, 'adminapp/products.html', context)


@user_passes_test(lambda u: u.is_superuser)
def products_update(request, pk):
    title = "продукт / редактирование"
    edit_product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="admin_container">        
        <div class="h2 text-center head">
            Админка
        </div>
        {% block menu %}
            <div class="admin_menu">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        {% endblock %}
        
        
        {% block content %}

        {% endblock %}
        
	</div>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/orders_scripts.js' %}"></script>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href={% url 'admin_stuff:category_create' %}>новая категория</a>
        </button>

        {% for object in objects %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href={% url 'admin_stuff:products' object.pk %}>товары категории</a>
                    </button>
                    <button>
                        <a href={% url 'admin_stuff:category_update' object.pk %}>редактировать</a>
                    </button>
                    <button>
                        {% if object.is_active == True %}
                        <a href={% url 'admin_stuff:category_delete' object.pk %}>удалить</a>
                        {% else %}
                        <a href={% url 'admin_stuff:category_delete' object.pk %}>восстановить</a>
                        {% endif %}
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите {% if object.is_active %}удалить{% else %}восстановить{% endif %}  категорию <strong>{{ object.name }}</strong>?
        <form action="{% url 'admin_stuff:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            {% if object.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
            <input class="btn btn-danger" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_stuff:categories' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin_stuff:categories' %}">
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_delete">
        Уверены, что хотите {% if product_to_delete.is_active %}удалить{% else %}восстановить{% endif %} продукт <strong>{{ product_to_delete.name }}</strong>?
        <form action="{% url 'admin_stuff:product_delete' product_to_delete.pk %}" method="post">
            {% csrf_token %}
            {% if product_to_delete.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
            <input class="btn btn-danger" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_stuff:products' product_to_delete.category.pk %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong> 
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin_stuff:products_update' object.pk %}>редактировать</a>
                </button>
            </p>
            <p>
                <button>
                    {% if object.is_active %}
                    <a href={% url 'admin_stuff:product_delete' object.pk %}>удалить</a>
                    {% else %}
                    <a href={% url 'admin_stuff:product_delete' object.pk %}>восстановить</a>
                    {% endif %}
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin_stuff:products' object.category.pk %}>назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>
                {{ object.short_desc }}
            </p>
            <br>
            <br>
            <b>подробная информация</b>
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin_stuff:products' category.pk %}">
                к списку продуктов
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="products_list">
		<button class="new_product">
			<a href={% url 'admin_stuff:products_create' category.pk %}>новый продукт</a>
		</button>
		
		{% for object in objects %}
			<div class="product_record {% if not object.is_active %}not_active{% endif %}">
				<img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
				<div class="product_name">
					{{ object.name|title }}
				</div>
				<div class="product_actions">
					<button>
						<a href={% url 'admin_stuff:product_read' object.pk %}>подробнее</a>
					</button>
					<button>
						<a href={% url 'admin_stuff:products_update' object.pk %}>редактировать</a>
					</button>
					<button>
                        {% if object.is_active %}
						<a href={% url 'admin_stuff:product_delete' object.pk %}>удалить</a>
                        {% else %}
                        <a href={% url 'admin_stuff:product_delete' object.pk %}>восстановить</a>
                        {% endif %}
					</button>
				</div>
				<div class="summary">
					<b>цена</b>
					<p>{{ object.price }} руб</p>
					<b>количество</b>
					<p>{{ object.quantity }}</p>
				</div>
				<div class="product_desc">
					{{ object.short_desc|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{#    <div class="pagination">#}
{#        {% if object.has_previous %}#}
{#            <a class="previous" href="{% url 'adminapp:page' category.pk object.previous_page_number %}">#}
{#                <#}
{#            </a>#}
{#        {% endif %}#}
{#        <span class="current">#}
{#            страница {{ object.number }} из {{ object.paginator.num_pages }}#}
{#        </span>#}
{#        {% if object.has_next %}#}
{#            <a class="next" href="{% url 'adminapp:page' category.pk object.next_page_number %}">#}
{#                >#}
{#            </a>#}
{#        {% endif %}#}
    </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите {% if user_to_delete.is_active %}удалить{% else %}восстановить{% endif %} {{ user_to_delete.username }} {% if user_to_delete.first_name %}
                    (<b>{{ user_to_delete.first_name|title }}</b>
                    {% if user_to_delete.last_name %}
                        {{ user_to_delete.last_name|title }}
                    {% endif %})
    {% endif %}?
        <form action="{% url 'admin_stuff:user_delete' user_to_delete.pk %}" method="post">
            {% csrf_token %}
            {% if user_to_delete.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
            <input class="btn btn-danger" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_stuff:users' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data" style="max-width: 800px; margin: auto;">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin_stuff:users' %}">
            к списку пользователей
        </a>
    </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="users_list">
		<button class="new_user">
			<a href={% url 'admin_stuff:user_create' %}>новый пользователь</a>
		</button>
		{% for object in object_list %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img src="{{ object.avatar|media_folder_user }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
					<button>
						<a href={% url 'admin_stuff:user_update' object.pk %}>редактировать</a>
					</button>
					<button>
                        {% if object.is_active == True %}
						<a href={% url 'admin_stuff:user_delete' object.pk %}>удалить</a>
                        {% else %}
                        <a href={% url 'admin_stuff:user_delete' object.pk %}>восстановить</a>
                        {% endif %}
					</button>
				</div>
				<div class="user_name">
					<p>
						<strong>{{ object.username }}</strong>
					</p>
					<p>
                    {% if object.first_name %}
                        <b>{{ object.first_name|title }}</b>
                        {% if object.last_name %}
                            <p>{{ object.last_name|title }}</p>
                        {% endif %}
                    {% endif %}
					</p>
				</div>
				<div class="user_age">
					age:<br>
					{{ object.age }} лет
				</div>
				<div class="user_email">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin">
					logged:<br>
					{{ object.last_login }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}